config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'accents/index'
  root to: "accents#index"
  resources :accents do
    resources :comments, only: :create
    resources :atamadakas, only: [:create, :destroy]
    resources :nakadakas, only: [:create, :destroy]
    resources :odakas, only: [:create, :destroy]
    resources :heibans, only: [:create, :destroy]

    collection do
      get 'search'
    end
  end
end

app/models/accent.rb
class Accent < ApplicationRecord
  # アソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :atamadakas, dependent: :destroy
  has_many :nakadakas, dependent: :destroy
  has_many :odakas, dependent: :destroy
  has_many :heibans, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :part_of_speech
  belongs_to :accent_pattern
  belongs_to :beat_count

  # アクセント登録時のバリデーション
  with_options presence: true do
    validates :info, length: { maximum: 400 }

    with_options length: { maximum: 20 } do
      validates :word, uniqueness: { case_sensitive: false }
      validates :word_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カタカナを入力してください' }
    end
  end
  
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :part_of_speech_id
    validates :accent_pattern_id
  end

  # searchアクションの定義
  def self.search(search)
    Accent.where('word LIKE(?)', "#{search}%") if search != ''
  end
end

app/models/accent_pattern.rb
class AccentPattern < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '頭高型' },
    { id: 3, name: '中高型' },
    { id: 4, name: '尾高型' },
    { id: 5, name: '平板型' }
  ]

  include ActiveHash::Associations
  has_many :accents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atamadaka.rb
class Atamadaka < ApplicationRecord
  belongs_to :accent
  belongs_to :user

  validates_uniqueness_of :accent_id, scope: :user_id
end

app/models/beat_count.rb
class BeatCount < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '2拍目' },
    { id: 3, name: '3拍目' },
    { id: 4, name: '4拍目' },
    { id: 5, name: '5拍目' },
    { id: 6, name: '6拍目' },
    { id: 7, name: '7拍目' },
    { id: 8, name: '8拍目' },
    { id: 9, name: '9拍目' },
    { id: 10, name: '10拍目' },
    { id: 11, name: '11拍目' },
    { id: 12, name: '12拍目' },
    { id: 13, name: '13拍目' },
    { id: 14, name: '14拍目' },
    { id: 15, name: '15拍目' },
    { id: 16, name: '16拍目' },
    { id: 17, name: '17拍目' },
    { id: 18, name: '18拍目' },
    { id: 19, name: '19拍目' }
  ]

  include ActiveHash::Associations
  has_many :accents
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :accent

  validates :comment, presence: true, length: { maximum: 200 }
end

app/models/heiban.rb
class Heiban < ApplicationRecord
  belongs_to :user
  belongs_to :accent

  validates_uniqueness_of :accent_id, scope: :user_id
end

app/models/nakadaka.rb
class Nakadaka < ApplicationRecord
  belongs_to :user
  belongs_to :accent

  validates_uniqueness_of :accent_id, scope: :user_id
end

app/models/odaka.rb
class Odaka < ApplicationRecord
  belongs_to :user
  belongs_to :accent

  validates_uniqueness_of :accent_id, scope: :user_id
end

app/models/part_of_speech.rb
class PartOfSpeech < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '名詞' },
    { id: 3, name: '動詞' },
    { id: 4, name: '形容詞' },
    { id: 5, name: '形容動詞' },
    { id: 6, name: '副詞' },
    { id: 7, name: '連体詞' },
    { id: 8, name: '接続詞' },
    { id: 9, name: '感動詞' },
    { id: 10, name: '数詞' },
    { id: 11, name: 'その他（上記＋付属語など）' }
  ]

  include ActiveHash::Associations
  has_many :accents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :password, format: { with: /\A[a-z0-9]+\z/i, message: 'は半角英数を入力してください' }

  has_many :accents
  has_many :comments
  has_many :atamadakas, dependent: :destroy
  has_many :nakadakas, dependent: :destroy
  has_many :odakas, dependent: :destroy
  has_many :heibans, dependent: :destroy

  def already_atamadaka?(accent)
    atamadakas.exists?(accent_id: accent.id)
  end

  def already_nakadaka?(accent)
    nakadakas.exists?(accent_id: accent.id)
  end

  def already_odaka?(accent)
    odakas.exists?(accent_id: accent.id)
  end

  def already_heiban?(accent)
    heibans.exists?(accent_id: accent.id)
  end
end

app/controllers/accents_controller.rb
class AccentsController < ApplicationController
  before_action :authenticate_user!, only: :new
  before_action :set_accent, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :delete]

  def index
    @accents = Accent.includes(:user).order('created_at DESC').limit(10)
  end

  def new
    @accent = Accent.new
  end

  def create
    @accent = Accent.new(accent_params)
    if @accent.valid?
      @accent.save
      redirect_to @accent
    else
      render action: :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @accent.comments.order('created_at DESC')
  end

  def edit
  end

  def update
    @accent.update(accent_params)
    if @accent.valid?
      redirect_to @accent
    else
      render action: :edit
    end
  end

  def destroy
    if @accent.destroy
      redirect_to action: :index
    else
      render action: :show
    end
  end

  def search
    @accents = Accent.search(params[:keyword])
  end

  private

  def accent_params
    params.require(:accent).permit(:word, :word_kana, :part_of_speech_id, :accent_pattern_id, :beat_count_id,
                                   :info).merge(user_id: current_user.id)
  end

  def set_accent
    @accent = Accent.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in? && (current_user.id == @accent.user.id || current_user.admin?)
  end
end

app/controllers/odakas_controller.rb
class OdakasController < ApplicationController
  def create
    @odaka = current_user.odakas.create(accent_id: params[:accent_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @accent = Accent.find(params[:accent_id])
    @odaka = current_user.odakas.find_by(accent_id: @accent.id)
    @odaka.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/accents_helper.rb
module AccentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atamadakas_helper.rb
module AtamadakasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/heibans_helper.rb
module HeibansHelper
end

app/helpers/nakadakas_helper.rb
module NakadakasHelper
end

app/helpers/odakas_helper.rb
module OdakasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>アクセント辞典</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/shared/_atamadaka.html.erb
<% if user_signed_in? %>
  <% if current_user.already_atamadaka?(accent) %>
    <%= link_to '頭高型', accent_atamadaka_path(accent), method: :delete %>
  <% else %>
    <%= link_to '頭高型', accent_atamadakas_path(accent), method: :post %>
  <% end %>
  <%= accent.atamadakas.count %>
<% else %>
  頭高型 <%= accent.atamadakas.count%>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <%= link_to "Accent辞典", root_path, class: "header-title" %>
  <ul class="header-lists">
    <% if user_signed_in? %>
      <li class="header-list">
        <%= current_user.nickname %>
      </li>
      <li class="header-list">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: "header-link" %>
      </li>
    <% else %>
      <li class="header-list">
        <%= link_to "ログイン", new_user_session_path, class: "header-link"%>
      </li>
      <li class="header-list">
        <%= link_to "新規登録", new_user_registration_path, class: "header-link" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_heiban.html.erb
<% if user_signed_in? %>
  <% if current_user.already_heiban?(@accent) %>
    <%= link_to '平板型', accent_heiban_path(@accent), method: :delete %>
  <% else %>
    <%= link_to '平板型', accent_heibans_path(@accent), method: :post %>
  <% end %>
  <%= @accent.heibans.count %>
<% else %>
  平板型 <%= @accent.heibans.count%>
<% end %>

app/views/shared/_nakadaka.html.erb
<% if user_signed_in? %>
  <% if current_user.already_nakadaka?(accent) %>
    <%= link_to '中高型', accent_nakadaka_path(accent), method: :delete %>
  <% else %>
    <%= link_to '中高型', accent_nakadakas_path(accent), method: :post %>
  <% end %>
    <%= accent.nakadakas.count %>
<% else %>
  中高型 <%= accent.nakadakas.count%>
<% end %>

app/views/shared/_odaka.html.erb
<% if user_signed_in? %>
  <% if current_user.already_odaka?(@accent) %>
    <%= link_to '尾高型', accent_odaka_path(@accent), method: :delete %>
  <% else %>
    <%= link_to '尾高型', accent_odakas_path(@accent), method: :post %>
  <% end %>
    <%= @accent.odakas.count %>
<% else %>
  尾高型 <%= @accent.odakas.count%>
<% end %>