config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'accents/index'
  root to: "accents#index"
  resources :accents do
    resources :comments, only: :create
    resources :atamadakas, only: [:create, :destroy]
    resources :nakadakas, only: [:create, :destroy]
    resources :odakas, only: [:create, :destroy]
    resources :heibans, only: [:create, :destroy]

    collection do
      get 'search'
    end
  end
end

app/models/accent.rb
class Accent < ApplicationRecord
  # アソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :atamadakas, dependent: :destroy
  has_many :nakadakas, dependent: :destroy
  has_many :odakas, dependent: :destroy
  has_many :heibans, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :part_of_speech
  belongs_to :accent_pattern
  belongs_to :beat_count

  # アクセント登録時のバリデーション
  with_options presence: true do
    validates :info, length: { maximum: 400 }

    with_options length: { maximum: 20 } do
      validates :word, uniqueness: { case_sensitive: false }
      validates :word_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カタカナを入力してください' }
    end
  end
  
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :part_of_speech_id
    validates :accent_pattern_id
  end

  # searchアクションの定義
  def self.search(search)
    Accent.where('word LIKE(?)', "#{search}%") if search != ''
  end
end

app/models/accent_pattern.rb
class AccentPattern < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '頭高型' },
    { id: 3, name: '中高型' },
    { id: 4, name: '尾高型' },
    { id: 5, name: '平板型' }
  ]

  include ActiveHash::Associations
  has_many :accents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atamadaka.rb
class Atamadaka < ApplicationRecord
  belongs_to :accent
  belongs_to :user

  validates_uniqueness_of :accent_id, scope: :user_id
end

app/models/beat_count.rb
class BeatCount < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '2拍目' },
    { id: 3, name: '3拍目' },
    { id: 4, name: '4拍目' },
    { id: 5, name: '5拍目' },
    { id: 6, name: '6拍目' },
    { id: 7, name: '7拍目' },
    { id: 8, name: '8拍目' },
    { id: 9, name: '9拍目' },
    { id: 10, name: '10拍目' },
    { id: 11, name: '11拍目' },
    { id: 12, name: '12拍目' },
    { id: 13, name: '13拍目' },
    { id: 14, name: '14拍目' },
    { id: 15, name: '15拍目' },
    { id: 16, name: '16拍目' },
    { id: 17, name: '17拍目' },
    { id: 18, name: '18拍目' },
    { id: 19, name: '19拍目' }
  ]

  include ActiveHash::Associations
  has_many :accents
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :accent

  validates :comment, presence: true, length: { maximum: 200 }
end

app/models/heiban.rb
class Heiban < ApplicationRecord
  belongs_to :user
  belongs_to :accent

  validates_uniqueness_of :accent_id, scope: :user_id
end

app/models/nakadaka.rb
class Nakadaka < ApplicationRecord
  belongs_to :user
  belongs_to :accent

  validates_uniqueness_of :accent_id, scope: :user_id
end

app/models/odaka.rb
class Odaka < ApplicationRecord
  belongs_to :user
  belongs_to :accent

  validates_uniqueness_of :accent_id, scope: :user_id
end

app/models/part_of_speech.rb
class PartOfSpeech < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '名詞' },
    { id: 3, name: '動詞' },
    { id: 4, name: '形容詞' },
    { id: 5, name: '形容動詞' },
    { id: 6, name: '副詞' },
    { id: 7, name: '連体詞' },
    { id: 8, name: '接続詞' },
    { id: 9, name: '感動詞' },
    { id: 10, name: '数詞' },
    { id: 11, name: 'その他（上記＋付属語など）' }
  ]

  include ActiveHash::Associations
  has_many :accents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :password, format: { with: /\A[a-z0-9]+\z/i, message: 'は半角英数を入力してください' }

  has_many :accents
  has_many :comments
  has_many :atamadakas, dependent: :destroy
  has_many :nakadakas, dependent: :destroy
  has_many :odakas, dependent: :destroy
  has_many :heibans, dependent: :destroy

  def already_atamadaka?(accent)
    atamadakas.exists?(accent_id: accent.id)
  end

  def already_nakadaka?(accent)
    nakadakas.exists?(accent_id: accent.id)
  end

  def already_odaka?(accent)
    odakas.exists?(accent_id: accent.id)
  end

  def already_heiban?(accent)
    heibans.exists?(accent_id: accent.id)
  end
end

app/controllers/accents_controller.rb
class AccentsController < ApplicationController
  before_action :authenticate_user!, only: :new
  before_action :set_accent, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :delete]

  def index
    @accents = Accent.includes(:user).order('created_at DESC').limit(10)
  end

  def new
    @accent = Accent.new
  end

  def create
    @accent = Accent.new(accent_params)
    if @accent.valid?
      @accent.save
      redirect_to @accent
    else
      render action: :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @accent.comments.order('created_at DESC')
  end

  def edit
  end

  def update
    @accent.update(accent_params)
    if @accent.valid?
      redirect_to @accent
    else
      render action: :edit
    end
  end

  def destroy
    if @accent.destroy
      redirect_to action: :index
    else
      render action: :show
    end
  end

  def search
    @accents = Accent.search(params[:keyword])
  end

  private

  def accent_params
    params.require(:accent).permit(:word, :word_kana, :part_of_speech_id, :accent_pattern_id, :beat_count_id,
                                   :info).merge(user_id: current_user.id)
  end

  def set_accent
    @accent = Accent.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in? && (current_user.id == @accent.user.id || current_user.admin?)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    redirect_to accent_path(params[:accent_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, accent_id: params[:accent_id])
  end
end

app/controllers/heibans_controller.rb
class HeibansController < ApplicationController
  def create
    @heiban = current_user.heibans.create(accent_id: params[:accent_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @accent = Accent.find(params[:accent_id])
    @heiban = current_user.heibans.find_by(accent_id: @accent.id)
    @heiban.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/nakadakas_controller.rb
class NakadakasController < ApplicationController
  def create
    @nakadaka = current_user.nakadakas.create(accent_id: params[:accent_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @accent = Accent.find(params[:accent_id])
    @nakadaka = current_user.nakadakas.find_by(accent_id: @accent.id)
    @nakadaka.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/odakas_controller.rb
class OdakasController < ApplicationController
  def create
    @odaka = current_user.odakas.create(accent_id: params[:accent_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @accent = Accent.find(params[:accent_id])
    @odaka = current_user.odakas.find_by(accent_id: @accent.id)
    @odaka.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/accents_helper.rb
module AccentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atamadakas_helper.rb
module AtamadakasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/heibans_helper.rb
module HeibansHelper
end

app/helpers/nakadakas_helper.rb
module NakadakasHelper
end

app/helpers/odakas_helper.rb
module OdakasHelper
end

app/views/accents/edit.html.erb
<div class="subscribe-contents">
  <header class="subscribe-header">
    <%= link_to 'Accent辞典', "/", class: "subscribe-header-text" %>
  </header>
  
  <div class="subscribe-main">
    <h2 class="subscribe-title">単語の情報を入力</h2>
    <%= form_with model: @accent, url: accent_path, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# 単語 %>
      <div class="word-name">
        <div class="weight-bold-text">
          単語
          <span class="indispensable">*</span>
        </div>
          <%= f.text_area :word, class:"word-text", id:"word-id", placeholder:"単語（20文字以内）", maxlength:"20" %>
        <div class="weight-bold-text">
          単語(フリガナ)
          <span class="indispensable">*</span>
        </div>
          <%= f.text_area :word_kana, class:"word-text", id:"word-kana-id", placeholder:"単語のフリガナ（20文字以内）", maxlength:"20" %>
      </div>
      <%# /単語 %>
    
      <%# 単語の品詞 %>
      <div class="word-details">
        <div class="weight-bold-text">
          単語の品詞
          <span class="indispensable">*</span>
        </div>
        <%= f.collection_select(:part_of_speech_id, PartOfSpeech.all, :id, :name, {}, {class:"select-box", id:"speech-select-id"}) %>
      </div>
      <%# /単語の品詞 %>

      <%# アクセントの型 %>
      <div class="word-details">
        <div class="weight-bold-text">
          アクセントの型
          <span class="indispensable">*</span>
        </div>
        <%= f.collection_select(:accent_pattern_id, AccentPattern.all, :id, :name, {}, {class:"select-box", id:"accent-pattern-id"}) %>
      </div>
      <%# /アクセントの型 %>

      <%# アクセントの高さの切れ目 %>
      <div class="word-details">
        <div class="weight-bold-text">
          高さの切れ目の拍(中高型の場合)
        </div>
        <%= f.collection_select(:beat_count_id, BeatCount.all, :id, :name, {}, {class:"select-box", id:"beat-count-id"}) %>
      </div>
      <%# /アクセントの高さの切れ目 %>

      <%# 情報源 %>
      <div class="word-info">
        <div class="weight-bold-text">
          情報源
          <span class="indispensable">*</span>
        </div>
          <%= f.text_area :info, class:"word-text", id:"info-id", placeholder:"テレビ番組や使用者の年代、地域など（400文字以内）", maxlength:"400" %>
      </div>
      <%# /情報源 %>

      <%# 下部ボタン %>
      <div class="subscribe-btn-contents">
        <%= f.submit "登録する", class:"word-subscribe-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/accents/index.html.erb
<%= render "shared/header" %>

<%# 検索フォーム %>
<div class="main-contents">
  <div class="search-contents">
    <h1 class="accent-search">アクセント検索</h1>
    <%= form_with(url: search_accents_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "調べたい単語を入力", class: "word-form" %>
      <%= f.submit "検索", class: "search-button" %>
    <% end %>
  </div>

  <%# 中央広告部分 %>
  <div class="app-intro">
    <div class="app-intro-left">
      <p class='service-explain'>
        アプリで簡単検索
      </p>
      <p class='service-explain'>
        単語登録もできる！
      </p>
    </div>
    <div class="app-intro-right">
      <p class='service-title'>
        Accent辞典
      </p>
      <div class='store-btn'>
        <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
        <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
      </div>
    </div>
  </div>
  
  <%# 新着ワード %>
  <div class="bottom-contents">
    <div class="hot-word">
      <h1>新着ワード</h1>
      <ul class="word-lists">
        <% @accents.each do |accent| %>
          <li class="word-list"><%= link_to "#{accent.word}", accent_path(accent) %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
  <%# 単語登録ボタン %>
    <%= link_to(new_accent_path, class: 'subscribe-btn') do %>
      <span class='subscribe-btn-text'>単語登録する</span>
    <!-- <%= image_tag 'icon_subscribe.png' , size: '120x120' ,class: "subscribe-btn-icon" %>-->
    <% end %>
</div>

app/views/accents/new.html.erb
<div class="subscribe-contents">
  <header class="subscribe-header">
    <%= link_to 'Accent辞典', "/", class: "subscribe-header-text" %>
  </header>
  
  <div class="subscribe-main">
    <h2 class="subscribe-title">単語の情報を入力</h2>
    <%= form_with model: @accent, url: accents_path, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# 単語 %>
      <div class="word-name">
        <div class="weight-bold-text">
          単語
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :word, class:"word-text", id:"word-id", placeholder:"単語（20文字以内）", maxlength:"20" %>
        <div class="weight-bold-text">
          単語(フリガナ)
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :word_kana, class:"word-text", id:"word-kana-id", placeholder:"単語のフリガナ（20文字以内）", maxlength:"20" %>
      </div>
      <%# /単語 %>
    
      <%# 単語の品詞 %>
      <div class="word-details">
        <div class="weight-bold-text">
          単語の品詞
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:part_of_speech_id, PartOfSpeech.all, :id, :name, {}, {class:"select-box", id:"speech-select-id"}) %>
      </div>
      <%# /単語の品詞 %>

      <%# アクセントの型 %>
      <div class="word-details">
        <div class="weight-bold-text">
          アクセントの型
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:accent_pattern_id, AccentPattern.all, :id, :name, {}, {class:"select-box", id:"accent-pattern-id"}) %>
      </div>
      <%# /アクセントの型 %>

      <%# アクセントの高さの切れ目 %>
      <div class="word-details">
        <div class="weight-bold-text">
          高さの切れ目の拍(中高型の場合)
        </div>
        <%= f.collection_select(:beat_count_id, BeatCount.all, :id, :name, {}, {class:"select-box", id:"beat-count-id"}) %>
      </div>
      <%# /アクセントの高さの切れ目 %>

      <%# 情報源 %>
      <div class="word-info">
        <div class="weight-bold-text">
          情報源
          <span class="indispensable">必須</span>
        </div>
          <%= f.text_area :info, class:"word-text", id:"info-id", placeholder:"テレビ番組や使用者の年代、地域など（400文字以内）", maxlength:"400" %>
      </div>
      <%# /情報源 %>

      <%# 下部ボタン %>
      <div class="subscribe-btn-contents">
        <%= f.submit "登録する" ,class:"word-subscribe-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/accents/search.html.erb
<%= render "shared/header" %>

<%# 検索フォーム %>
<div class="main-contents">
  <div class="search-contents">
    <h1 class="accent-search">アクセント検索</h1>
    <%= form_with(url: search_accents_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "調べたい単語を入力", class: "word-form" %>
      <%= f.submit "検索", class: "search-button" %>
    <% end %>
  </div>

<%# 中央広告部分 %>
  <div class="app-intro">
    <div class="app-intro-left">
      <p class='service-explain'>
        アプリで簡単検索
      </p>
      <p class='service-explain'>
        単語登録もできる！
      </p>
    </div>
    <div class="app-intro-right">
      <p class='service-title'>
        Accent辞典
      </p>
      <div class='store-btn'>
        <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
        <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
      </div>
    </div>
  </div>
  
  <%# 検索候補ワード %>
  <div class="bottom-contents">
    <div class="hot-word">
      <h1>検索候補ワード</h1>
      <% if @accents != [] %>
        <ul class="word-lists">
          <% @accents.each do |accent| %>
            <li class="word-list"><%= link_to "#{accent.word}", accent_path(accent) %></li>
          <% end %>
        </ul>
      <% else %>
        <strong><p>検索ワードは見つかりませんでした</p></strong> 
      <% end%>
    </div>
  </div>
  
  <%# 単語登録ボタン %>
    <%= link_to(new_accent_path, class: 'subscribe-btn') do %>
      <span class='subscribe-btn-text'>単語登録する</span>
    <!-- <%= image_tag 'icon_subscribe.png' , size: '120x120' ,class: "subscribe-btn-icon" %>-->
    <% end %>
</div>

app/views/accents/show.html.erb
<%= render "shared/header" %>

<div class="show-contents">
  
  <div class="show-main-contents">
    <div class="word">
      <div class="show-word-pattern">
        <%= @accent.part_of_speech.name %>
      </div>
      <div class="show-accent-word">
      <!-- 登録された情報によってアクセントの下り目の位置を決める -->
        <% if @accent.accent_pattern_id == 2 %>
          <%= @accent.word_kana.insert( 1, '＼') %>
        <% elsif @accent.accent_pattern_id == 3 %>
          <%= @accent.word_kana.insert( @accent.beat_count_id, '＼') %>
        <% elsif @accent.accent_pattern_id == 4 %>
          <%= @accent.word_kana.insert( @accent.word_kana.length, '＼') %>
        <% elsif @accent.accent_pattern_id == 5 %>
          <%= @accent.word_kana.insert( @accent.word_kana.length, '￣')%>
        <% end %>
      <!-- /登録された情報によってアクセントの下り目の位置を決める -->
        <% if user_signed_in? && current_user.id == @accent.user_id %>
          <%= link_to "編集", edit_accent_path(@accent), class: "edit-btn" %>
        <% end %>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to "削除", accent_path(@accent), class: "delete-btn", method: :delete %>
        <% end %>
        <!--<span class="report-btn">通報</span>-->
      </div>
      <div class="show-word">
        （<%= @accent.word %>）
      </div>
    </div>
  
    <div class="show-accent">
      <div class="show-accent-title">
        アクセントの型
      </div>
      <div class="accent-pattern">
        <%= @accent.accent_pattern.name%>
      </div>
    </div>

    <div class="show-info">
      <div class="show-info-title">
        情報源
      </div>
      <div class="info">
        <%= @accent.info %>
      </div>
    </div>

    <div class="use-examle"><%# ←このクラス必要ない？ %>
      <div class="use-example-pattern">
        他の使用例
      </div>
      <ul class="pattern-lists">
        <li class="pattern-list", id="atamadaka-<%= @accent.id %>">
          <%# 非同期通信用のrender %>
          <%#= render partial: "atamadakas/atamadaka", locals: { accent: @accent, atamadakas: @atamadakas } %>
          <%= render partial: "shared/atamadaka", locals: { accent: @accent } %>
        </li>
        <li class="pattern-list">
          <%= render partial: "shared/nakadaka", locals: { accent: @accent } %>
        </li>
        <li class="pattern-list">
          <%= render partial: "shared/odaka", locals: { accent: @accent } %>
        </li>
        <li class="pattern-list">
          <%= render partial: "shared/heiban", locals: { accent: @accent} %>
        </li>
      </ul>
    </div>
  
  </div>
  
  <div class="show-comments">
    <div class="comment-title">
      コメント
    </div>
    <% if user_signed_in? %>
      <%= form_with model: [@accent, @comment], class: "comment-form", local: true do |f| %>
        <%= f.text_area :comment, class: "comment-text", rows: "3", maxlength: "200" %>
        <%= f.submit "コメントする", class: "comment-btn" %>
      <% end %>
    <% else %>
      <strong><p>*** コメントの投稿には新規登録/ログインが必要です ***</p></strong>
    <% end %>
    <ul class="comments">
      <% @comments.each do |comment| %>
        <li class="comment">
          <%= comment.user.nickname %>(<%= l comment.created_at %>)
          <p><%= comment.comment %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>